
spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/domain
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:/org/springframework/batch/core/schema-h2.sql
#      mode: always # always: ?? ??, never: ?? ? ?, embedded: ?? DB? ?? ??, ?? ?? ? ??. ?? already exists ?? ??
      continue-on-error: true # ?? ???? ?? ??
  batch:
    job:
      enabled: false # false ? ? ??? ?? ?? ? ?
